apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i93lg4thg-go 
  janus-idp.io/tekton: i93lg4thg-go
  backstage.io/kubernetes-id: i93lg4thg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i93lg4thg-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  